# workflow name
name: Test on Push
# workflow is executed on every push to a feature branch
on:
  push:
    branches:
      - develop
# jobs are run independently of one another
jobs: 
  test:
    # target machine on which job is run
    runs-on: ubuntu-latest 
    steps:
      # step runs a premade Action to checkout the repo
      - uses: actions/checkout@v2
      # custom steps that run in a shell
      - name: Hello world
	run: |
	  echo "Hello World"
      - name: Run Tests
        run: |
          make test
